Milestone 2.1: Blog app: add devise
Gardimy/BlogApp pull request #20
Opened 2023-11-07 19:40 UTC by Gardimy

In this project, My coding partner and l added the [devise](https://github.com/heartcombo/devise) gem to our app and used it for the registration and login of users.

2023-11-07 22:03 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- The gem required to enable authentication have been added :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 22:03 UTC, FrederickMih commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] Hi team, nice job for adding the gem (`gem 'devise'`) that enables registration and authentication. You also did a great job adding the registration and login form but unfortunately a user can't successfully register into this app. The current_user method in the ApplicationController was supposed to have been removed since devise provide a method for this specific. For the application to allow user to register, log in, ask for email confirmation, reset a password, the following should be enabled in the user model
```
devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :validatable, :confirmable
```

- Let's kindly double-check and make sure authentication is properly configured. When I run this app, I was not ask to register as you can see below:
![Screenshot from 2023-11-07 22-57-28](https://github.com/Gardimy/BlogApp/assets/63087491/6cd58222-08ce-4f7c-917f-07c4c18a52ab)

2023-11-08 03:32 UTC, elisha2kyakpo1 requested changes
Hi 👋 team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

👍 You did well fixing some issues requested by the previous reviewer

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 03:32 UTC, elisha2kyakpo1 commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
- [ ] One more important attribute is missing, kindly add `:confirmable` to the devise for user here to help make email confirmation easier.

2023-11-08 03:32 UTC, elisha2kyakpo1 commented on app/views/welcome/inde.html.erb
> +  <style>
- [ ] Let's create a CSS file in the assets folder/stylesheets and put out CSS code there. Inline styling is always discouraged.

2023-11-09 19:00 UTC, cynthiainga approved these changes
Hi @Gardimy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] All changes are made ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 19:01 UTC, merged