Milestone 6 : Blog app - Views
Gardimy/BlogApp pull request #6
Opened 2023-09-08 13:49 UTC by Gardimy

In this milestone, I add the Views associated with the Models and Controllers I've already created for my Blog App.

2023-09-08 20:20 UTC, Munsa1 requested changes
Hi @Gardimy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Implemented Views :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Due to insufficient files changed I will leave comments here

### :warning: Important :warning: 
- [ ] Kindly fix the duplicate `Getting Started` sections in your readme by removing one
- [ ] Kindly fix the link to your `LinkedIn` profile under the author section of your readme file as it is broken
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 20:20 UTC, Munsa1 commented on app/views/users/index.html.erb
> +</ul>
- [ ] Great job implementing the user index page however we must follow the given wireframe for layout of elements and components on the page.

Your design
![image](https://github.com/Gardimy/BlogApp/assets/81932478/1985c6ef-5066-4846-ade4-3069c7c182be)

Given frame
![image](https://github.com/Gardimy/BlogApp/assets/81932478/cdf483cc-a91a-44a8-8d18-9f884b76f338)

- Kindly implement the image in your design
- Kindly implement the number of posts

#### Please NOTE that the image should be to the left and the `User` name `Number of posts` should be positioned as is in the wireframe

2023-09-08 20:20 UTC, Munsa1 commented on app/views/users/show.html.erb
> +    <%= link_to "See all posts", user_posts_path(@user) %>
- [ ] Great job implementing the user show page, however here again we should follow the given wireframe design and element implementation.

Your design
![image](https://github.com/Gardimy/BlogApp/assets/81932478/078473c2-0abd-47b5-b17d-da5b268e20c6)


Given design
![image](https://github.com/Gardimy/BlogApp/assets/81932478/1987bdc2-a23b-4549-aca4-85e528136fc2)

- The user image should be present
- User name and number of posts should follow the layout in the wireframe
- The Bio should be positioned as in the given design
- Each post should follow the layout of the given wireframe and should include the number of comments and likes. Note that these should not be hardcoded but should be actual values depending on how many comments and likes a user has. Of course, likes will be implemented later.


- [ ] Here we should use `#recent_posts` method created in the User model to render the user's 3 most recent post. Kindly fix this.

2023-09-08 20:20 UTC, Munsa1 commented on app/views/posts/index.html.erb
>  </html>
- [ ] Again kindly fix your design to follow the given wireframe.

Your design
![image](https://github.com/Gardimy/BlogApp/assets/81932478/b9ff870e-5018-474b-9a7d-6de69421763d)


Given design
![image](https://github.com/Gardimy/BlogApp/assets/81932478/8f460493-b934-49cd-9510-1680b27374b1)


- The image should be present
- Username and number of posts should be present
- Each post should show comments and a number of likes


- [ ] Here we should use the `post.recent_comments` method created in the Post model to render 5 most recent comments in the `app/views/posts/index.html.erb` page

2023-09-08 20:20 UTC, Munsa1 commented on app/views/posts/index.html.erb
> +          <% end %>
- [ ] (Optional) It would be nice if by clicking on each post, a user would be taken to the user post show page.

2023-09-08 20:20 UTC, Munsa1 commented on app/views/posts/show.html.erb
> +</div>
- [ ] Kindly fix the route to the post-show page, as I am unable to access the page, I get the following error
![image](https://github.com/Gardimy/BlogApp/assets/81932478/55c210d0-147b-4426-b10a-ad6c050c46b4)

Kindly also ensure when you do that you fix your design to match the given layout below
![image](https://github.com/Gardimy/BlogApp/assets/81932478/a2d9e01e-0770-4203-bb2d-42a8728909f4)

2023-09-10 00:31 UTC, Owusu-Desmond approved these changes
Hi @Gardimy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-10 02:19 UTC, merged